// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLpLIPunuZnRZ2XHntpUgkl7MyXOv6hjE',
    appId: '1:1066353007593:web:19671d8fbfa868fe91c978',
    messagingSenderId: '1066353007593',
    projectId: 'addon-9498b',
    authDomain: 'addon-9498b.firebaseapp.com',
    storageBucket: 'addon-9498b.appspot.com',
    measurementId: 'G-H965RD3VJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzb3Y55ILx6OhTocSMY--dVnjFTL-9_o',
    appId: '1:1066353007593:android:efed34a4182faed091c978',
    messagingSenderId: '1066353007593',
    projectId: 'addon-9498b',
    storageBucket: 'addon-9498b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvIACMLPlGteC8EBRPFvsSTrmBNk_N2w',
    appId: '1:1066353007593:ios:62d61e7e634433c591c978',
    messagingSenderId: '1066353007593',
    projectId: 'addon-9498b',
    storageBucket: 'addon-9498b.appspot.com',
    iosBundleId: 'com.example.addon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZvIACMLPlGteC8EBRPFvsSTrmBNk_N2w',
    appId: '1:1066353007593:ios:1c20194ca6a2ed5291c978',
    messagingSenderId: '1066353007593',
    projectId: 'addon-9498b',
    storageBucket: 'addon-9498b.appspot.com',
    iosBundleId: 'com.example.addon.RunnerTests',
  );
}
